FROM ghcr.io/niangthree/nodejs:latest

ENV NAME=Pipeops \
    CFIP=icook.hk \
    ARGO_DOMAIN=pipeops.ct8.pp.ua \
    ARGO_AUTH=eyJhIjoiZDQzMzYxM2ZmODQxNWMyMGM3NDY0YTFkN2M2OWE2MDEiLCJ0IjoiYmFmZjc0MmMtMWNmOC00NGUyLWIzYjktMjRmN2ViYTI0ZTRkIiwicyI6IlpETXlPRGxoTm1VdFpEQmtOQzAwTTJRMUxXSXpZekV0Tm1NNU5qazFPV1F5TVRVeiJ9
